controller_list:
  - name: fake_joint_1_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
  - name: fake_joint_2_controller
    type: $(arg fake_execution_type)
    joints:
      - joint3
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - joint4
initial:  # Define initial robot poses.
  - group: gripper
    pose: default